Start = Comment;

(* Comment *)
Comment = SingleLineComment | MultiLineComment;

MultiLineComment = "/*" MultiLineCommentChars "*/";
MultiLineCommentChars = /[^*]+/ | "*" PostAsteriskCommentChars | "";
PostAsteriskCommentChars = MultiLineNotForwardSlashOrAsteriskChar MultiLineCommentChars
                         | "*" PostAsteriskCommentChars;
MultiLineNotForwardSlashOrAsteriskChar = /[^\/*]+/;

SingleLineComment = "//" SingleLineCommentChars;
SingleLineCommentChars = /[^\n]+/ | "";
